services:
  analyzer:
    build: 
      context: .
      target: analyzer
    stdin_open: true
    tty: true
    command: ["python3", "app.py", "--data", "/home/jovyan/data/KL Policies and Plans", "/home/jovyan/data/National Policies", "-s"]
    volumes:
      - ./:/home/jovyan/analyzer
      - ../Malaysia 1:/home/jovyan/data
    working_dir: /home/jovyan/analyzer
    environment:
      - AI_API_KEY=sk-KbR-Csnj0L7vUssXqZJQew